name: released

on:
  workflow_dispatch:

jobs:
  virustotal:
    uses: mort666/.github/.github/workflows/app-virustotal.yml@master
    secrets:
      vt_api_key: ${{ secrets.VT_API_KEY }}
      vt_monitor_api_key: ${{ secrets.VT_MONITOR_API_KEY }}
